// ─── Section Wars Rulebook — Structured Data ───
// Extracted from the ISB PGP Co'28 O-Week Rulebook PDF

import type { KTContentBlock, KTSubsection, KTSection } from "./kt-data";

// Re-export the types for convenience
export type RulebookContentBlock = KTContentBlock;
export type RulebookSubsection = KTSubsection;
export type RulebookSection = KTSection;

// ─── Section 1: Professional Events ───

const PROFESSIONAL_EVENTS: RulebookSection = {
  id: "professional",
  title: "Professional",
  icon: "Briefcase",
  color: "text-blue-600",
  emoji: "💼",
  subsections: [
    {
      id: "pro-case-competition",
      title: "Case Competition — AI & External Assistance Policy",
      content: [
        {
          type: "paragraph",
          text: "These instructions apply to all case competitions conducted during O Week. Teams are expected to use independent judgment and submit work that reflects their own thinking.",
        },
        { type: "heading", text: "Permitted Use" },
        {
          type: "list",
          items: [
            "Using AI tools for basic research, idea generation, concept clarification, or formatting suggestions.",
            "Using AI tools to improve your own draft after you have created the core analysis, model, and recommendation yourselves.",
            "Using AI tools to check grammar, wording, or presentation flow.",
          ],
        },
        { type: "heading", text: "Not Permitted" },
        {
          type: "list",
          items: [
            "Using AI tools to generate the final PPT, memo, write-up, or Excel model and submitting it as-is.",
            "Copy-pasting text, analysis, tables, formulas, charts, sources, or citations generated by AI directly into the submission.",
            "Using AI-generated content that the team cannot fully explain, defend, or reproduce.",
            "Using fabricated data, assumptions, references, or sources produced by AI.",
          ],
        },
        { type: "heading", text: "Submission Integrity" },
        {
          type: "list",
          items: [
            "All final analysis, recommendations, slides, write-ups, and models must represent the team's own work.",
            "If organizers or judges ask follow-up questions, teams must be able to explain the logic, assumptions, and calculations used in their submission.",
            "Any submission found to contain directly copied AI-generated content or an AI-generated model/deck may be disqualified.",
            "The organizers reserve the right to review any submission and to take an integrity call based on the quality of explanation during Q&A.",
          ],
        },
        {
          type: "callout",
          text: "By participating in the competition, each team agrees to comply with the above instructions. Any violation may result in disqualification at the discretion of the organizers and judges.",
          variant: "warning",
        },
      ],
    },
  ],
};

// ─── Section 2: Sports Events ───

const SPORTS_EVENTS: RulebookSection = {
  id: "sports",
  title: "Sports",
  icon: "Trophy",
  color: "text-green-600",
  emoji: "🏆",
  subsections: [
    {
      id: "sports-badminton",
      title: "Badminton",
      content: [
        { type: "heading", text: "Format" },
        {
          type: "list",
          items: [
            "6 sections will be divided into 2 groups of 3 sections each. Each section in a group will have a matchup tie with 2 other sections in that assigned group.",
            "The top team from each group will qualify for the Finals, and the second-placed teams from each group will play the overall third place match.",
            "Each Tie will have 3 matches (Men's Doubles, Women's Doubles and Mixed Doubles). Some matches can happen simultaneously on multiple courts as per constraints.",
          ],
        },
        { type: "heading", text: "Match Rules" },
        {
          type: "list",
          items: [
            "All matches (group stage + third place match) will be played in best of 3 sets format, each set will be played in an 11-point format; the Finals will have the sets extended to 15 points.",
            "No one player can play 2 or more matches in the same tie.",
            "A team should have 6 different players (3M + 3W) to play a Tie.",
            "Every team will have to share their team list at least 10 minutes before the scheduled time and specify the players partaking in the matches for that tie.",
          ],
        },
        { type: "heading", text: "Gameplay Rules" },
        {
          type: "list",
          items: [
            "Each match will begin with a toss. The winner of the toss can choose the side of the court they wish to start from or to serve/receive.",
            "The serve will change when a point is lost.",
            "Players will change sides after each set.",
            "If a game is tied at 11-11, the tie will go to deuce and \"difference of 2\" rule will be applicable.",
            "In case a player hits the shuttle into/against the ceiling/light the player's opponent will be awarded the point.",
          ],
        },
        { type: "heading", text: "Tiebreakers" },
        {
          type: "paragraph",
          text: "If teams are tied on league table points, the following tiebreakers will be applied in order:",
        },
        {
          type: "list",
          ordered: true,
          items: [
            "Match difference",
            "Set difference",
            "Point difference",
            "Coin toss",
          ],
        },
        { type: "heading", text: "Walkover Rules" },
        {
          type: "paragraph",
          text: "All walkovers will be treated as the match/tie was played and they lost every point/game/match.",
        },
        {
          type: "table",
          headers: ["Scenario", "Result"],
          rows: [
            ["Match Walkover (fail to field players for a match)", "Recorded as 2-0 win, each set 11-0"],
            ["Tie Walkover (fail to turn up for the Tie)", "3-0 in matches, 6-0 in sets, 66-0 in points; opposing team gets 3 league table points"],
            ["Absent team", "0 league table points, -3 match diff, -6 set diff, -66 point diff"],
            ["Both teams fail to turn up", "Both get 0 points, -3 match diff, -6 set diff, -66 point diff"],
          ],
        },
        {
          type: "callout",
          text: "Any rule not mentioned above will follow standard badminton rules as per worldbadminton.com/rules/.",
          variant: "info",
        },
      ],
    },
    {
      id: "sports-frisbee",
      title: "Frisbee",
      content: [
        { type: "heading", text: "Format" },
        {
          type: "list",
          items: [
            "6 sections will be divided into 2 groups of 3 sections each. Each section in a group will have a matchup tie with 2 other sections in that assigned group.",
            "A team will be awarded 3 league table points if they win a Tie.",
            "The top team from each group will qualify for the Finals, and the second-placed teams from each group will play the overall third place match.",
          ],
        },
        { type: "heading", text: "Match Rules" },
        {
          type: "list",
          items: [
            "Duration of each match is 2 halves of 12.5 mins each or up till one team scores 11 points.",
            "Half time will be after 12.5 minutes or when one team scores 6 points, whichever is earlier.",
            "6 players on field per team and minimum of 2 FEMALE players must be present on field at all times and unlimited substitutes per team (Rolling).",
            "Rolling substitutions can happen only when a point is scored or if a player is injured during an injury timeout (Not during the point).",
            "After a point is scored both teams have a maximum of 1 minute to start the next point. Failure to do so will lead to a warning, post which a point will be awarded to the opponent team.",
            "No physical contact is allowed between players. Picks and screens are also prohibited. A foul occurs when contact is made.",
            "If scores are tied at the end of full time, then the team to score the first additional point wins.",
          ],
        },
        { type: "heading", text: "Tiebreakers" },
        {
          type: "paragraph",
          text: "If the league table points are tied between teams, the following tie-breaking criteria will be applied in order:",
        },
        {
          type: "list",
          ordered: true,
          items: [
            "Point difference (points scored - points conceded)",
            "Points scored",
            "Points conceded",
            "Coin toss",
          ],
        },
        { type: "heading", text: "Walkover Rules" },
        {
          type: "table",
          headers: ["Scenario", "Result"],
          rows: [
            ["One team fails to turn up", "11-0 win for present team, 3 league table points"],
            ["Absent team", "0 league table points, point difference of -11"],
            ["Both teams fail to turn up", "Both get 0 league table points, point difference of -11"],
          ],
        },
        {
          type: "callout",
          text: "Any rule not mentioned above will follow standard rules as per wfdf.org.",
          variant: "info",
        },
      ],
    },
    {
      id: "sports-tug-of-war",
      title: "Tug of War",
      content: [
        { type: "heading", text: "Format" },
        {
          type: "list",
          items: [
            "6 sections will be divided into 2 groups of 3 sections each. Each section in a group will have a matchup tie with 2 other sections in that assigned group.",
            "A team will be awarded 3 league table points if they win a Tie.",
            "The top team from each group will qualify for the Finals, and the second-placed teams from each group will play the overall third place match.",
          ],
        },
        { type: "heading", text: "Match Rules" },
        {
          type: "list",
          items: [
            "Each Tie will consist of one Tug of War match played in a best of 5 pulls format. The team that wins 3 pulls first will be declared the winner of the Tie.",
            "Each team must field 12 players, with a minimum of 4 FEMALE participants for every match.",
            "Teams must submit their list of 12 players at least 10 minutes before the scheduled time of the Tie.",
            "No substitutions will be allowed once the match begins unless a player is unable to continue due to injury and approval is granted by the referee.",
          ],
        },
        { type: "heading", text: "Gameplay Rules" },
        {
          type: "list",
          items: [
            "Each pull will begin with the rope positioned such that the center mark on the rope is aligned with the ground center line. The referee will signal the start of the pull using a whistle.",
            "A pull will be declared won when a team successfully pulls the rope such that the center mark crosses the designated win line on their side.",
            "Teams will switch sides after each pull to ensure fairness with respect to ground conditions.",
            "Players must remain standing and pull using only their hands and body weight. Sitting, lying down, anchoring the rope to the ground, or wrapping the rope around the body or clothing is strictly prohibited.",
            "In case of unsafe conduct or violation of the rules, the referee may issue a warning or award the pull to the opposing team, depending on the severity of the violation.",
          ],
        },
        { type: "heading", text: "Tiebreakers" },
        {
          type: "paragraph",
          text: "If the league table points are tied between teams, the following tie-breaking criteria will be applied in order:",
        },
        {
          type: "list",
          ordered: true,
          items: [
            "Pull difference (pulls won - pulls lost)",
            "Head-to-head result (only if two teams are tied)",
            "Coin toss",
          ],
        },
        { type: "heading", text: "Walkover Rules" },
        {
          type: "table",
          headers: ["Scenario", "Result"],
          rows: [
            ["One team fails to turn up", "3-0 win for present team, 3 league table points"],
            ["Absent team", "0 league table points, pull difference of -3"],
            ["Both teams fail to turn up", "Both get 0 league table points, pull difference of -3"],
          ],
        },
        {
          type: "callout",
          text: "Any rule not mentioned above will follow standard international tug of war regulations.",
          variant: "info",
        },
      ],
    },
    {
      id: "sports-dodgeball",
      title: "Dodgeball",
      content: [
        { type: "heading", text: "Format" },
        {
          type: "list",
          items: [
            "6 sections will be divided into 2 groups of 3 sections each. Each section in a group will have a matchup tie with the 2 other sections in that assigned group.",
            "A team will be awarded 3 league table points if they win a Tie.",
            "The top team from each group will qualify for the Finals, and the second-placed teams from each group will play the overall third place match.",
            "Each Tie will consist of 2 rounds, where each team gets a chance to attack (outside the circle) and defend (inside the circle).",
            "Each round will have a maximum duration of 7 minutes.",
          ],
        },
        { type: "heading", text: "Setup & Objective" },
        {
          type: "list",
          items: [
            "At the start of each round, 20 players from the defending team will be inside the circle, and the remaining players from the attacking team will be positioned outside the circle.",
            "The attacking team aims to eliminate all 20 defenders in the shortest time possible.",
            "The defending team aims to survive as long as possible without getting eliminated.",
          ],
        },
        { type: "heading", text: "Elimination Rules" },
        {
          type: "list",
          items: [
            "A player is OUT if they are hit below the waist by a valid throw.",
            "A player is NOT OUT if the ball hits them above the waist.",
            "All decisions will be based on the point of impact at the time of contact.",
          ],
        },
        { type: "heading", text: "Scoring System (Per Round)" },
        {
          type: "table",
          headers: ["Scenario", "Attacking Team Score", "Defending Team Score"],
          rows: [
            ["All defenders eliminated within 7 min", "Time taken (lower is better)", "0"],
            ["Defenders remain after 7 min", "Number of eliminations", "Number of players remaining"],
          ],
        },
        { type: "heading", text: "Tie Result" },
        {
          type: "paragraph",
          text: "Each team will play 1 attacking and 1 defending round. For each attacking round:",
        },
        {
          type: "list",
          items: [
            "Eliminating all 20 defenders within 7 minutes (i.e., recording a time) is considered a better performance than any incomplete elimination.",
            "Among teams that achieve an all-out, the team with the lower time taken to eliminate all defenders performs better.",
            "If neither team achieves an all-out, the team with more eliminations performs better.",
            "The winner of the Tie will be decided based on the overall performance across both rounds (attacking + defending), taking into account both attacking output and defensive survival.",
          ],
        },
        { type: "heading", text: "Tiebreakers (League Stage)" },
        {
          type: "paragraph",
          text: "If teams are tied on league table points, the following tie-breaking criteria will be applied in order:",
        },
        {
          type: "list",
          ordered: true,
          items: [
            "Total eliminations (across all matches)",
            "Total players survived (across all matches)",
            "Coin toss",
          ],
        },
        { type: "heading", text: "Walkover Rules" },
        {
          type: "table",
          headers: ["Scenario", "Result"],
          rows: [
            ["One team fails to turn up", "20 eliminations + 20 players survived for present team, 3 league table points"],
            ["Absent team", "0 league table points, 0 eliminations, 0 players survived"],
            ["Both teams fail to turn up", "Both get 0 league table points, 0 eliminations, 0 players survived"],
          ],
        },
      ],
    },
  ],
};

// ─── Section 3: Social & Cultural Events ───

const SOCIAL_CULTURAL: RulebookSection = {
  id: "social-cultural",
  title: "Social & Cultural",
  icon: "PartyPopper",
  color: "text-purple-600",
  emoji: "🎭",
  subsections: [
    {
      id: "sc-souk",
      title: "Souk Al-Layl — Arabian Nights Carnival",
      content: [
        {
          type: "table",
          headers: ["Detail", "Info"],
          rows: [
            ["Date", "17 April 2026 (Thursday)"],
            ["Venue", "REC Center Lawns"],
            ["Theme", "Arabian Nights — Souk Al-Layl"],
            ["Events", "Section Carnival + Canvas Painting + Talent Show"],
            ["Stall Setup Budget", "₹10,000 (stall setup: chairs, tables, electrical connections)"],
          ],
        },
        { type: "heading", text: "1. Section Carnival Format" },
        {
          type: "paragraph",
          text: "Each section can set up 2 stalls:",
        },
        {
          type: "list",
          items: [
            "1 Food & Beverages Stall — Food or beverages only. No cooking gas allowed.",
            "1 Free Stall — Games, quirky ideas, creative merchandise, or anything that earns money.",
            "Stall ideas are approved on a first come, first serve basis. Once approved, no other section can copy the same idea.",
            "Max 5 members per stall. Choose your squad wisely.",
          ],
        },
        { type: "heading", text: "2. Important Dates" },
        {
          type: "table",
          headers: ["Deadline", "Action Required"],
          rows: [
            ["14 April 2026", "Submit both stall ideas (F&B + Free Stall) to the O-Week Team. Once approved, no other section can use or copy the same idea."],
            ["15 April 2026", "Submit pricing justification for all items/games. The O-Week Team will approve all pricing to ensure fairness across stalls."],
            ["15 April 2026 by 7:00 PM", "Final pricing approval deadline. Unfair or over-inflated pricing will be rejected."],
            ["16 April 2026", "Talent Show nominations (section or individual acts) to be submitted to O-Week Team."],
          ],
        },
        { type: "heading", text: "3. Token System" },
        {
          type: "list",
          items: [
            "Only O-Week Tokens will be used as currency. 1 Token = ₹50.",
            "All items/services must be priced in multiples of ₹50 (e.g. ₹50, ₹100, ₹150).",
            "Tokens can be purchased from the O-Week team counter during the carnival by all attendees.",
            "UPI / Cash transactions are allowed to buy Tokens; only O-Week Tokens can be used at stalls.",
            "Stall Owners can redeem tokens collected from sales at the end of the day.",
          ],
        },
        {
          type: "callout",
          text: "Token Counter Timing — Opens: 5:30 PM | Closes: 8:30 PM | Stall owners must redeem tokens by 9:30 PM latest.",
          variant: "info",
        },
        { type: "heading", text: "4. Revenue & Payouts" },
        {
          type: "list",
          items: [
            "75% of total earnings (in tokens) will be paid out to stall owners.",
            "25% will be retained by the O-Week team to cover carnival operational costs (decor, logistics, etc.).",
          ],
        },
        { type: "heading", text: "5. Canvas Painting" },
        {
          type: "list",
          items: [
            "Each section will be provided with a blank canvas and art supplies.",
            "A theme will be provided, and each section has liberty to brainstorm and interpret it in their own unique way, reflecting their group's essence, spirit, and identity.",
          ],
        },
        { type: "heading", text: "6. Talent Show" },
        {
          type: "list",
          items: [
            "A Talent Show will run simultaneously alongside the carnival on the REC Center Lawns stage.",
            "Sections or individuals can nominate themselves to perform.",
            "Nominations must be submitted by 16 April 2026 to the O-Week Team.",
            "Participation in the Talent Show contributes to the Best Team Spirit award.",
          ],
        },
        { type: "heading", text: "7. Awards" },
        {
          type: "table",
          headers: ["Award", "Criteria", "Weightage"],
          rows: [
            ["Best Section", "Highest net revenue earned", "30%"],
            ["Best F&B Stall", "Best taste, Creativity, Hygiene maintenance and Aesthetics", "25%"],
            ["Best Games Stall", "Creative idea and Execution", "25%"],
            ["Best Canvas", "Creativity, Best execution & output and Theme adherence", "15%"],
            ["Best Team Spirit", "Best spirit throughout the carnival, Participation in the talent show and participation in the canvas painting", "15%"],
          ],
        },
        {
          type: "callout",
          text: "Incognito Awards: Surprise awards announced at the end of the carnival — categories kept secret! Includes awards like Best Seller and more. Stay on your toes.",
          variant: "tip",
        },
        { type: "heading", text: "8. General Rules & Expectations" },
        {
          type: "list",
          items: [
            "No Duplication of Ideas: Once your stall idea is submitted and approved, no other section can copy it. Originality = Respect.",
            "Team Limit per Stall: Max 5 members per stall.",
            "Hygiene & Safety First: Especially for F&B stalls — no uncooked/raw food and basic food hygiene is non-negotiable.",
            "Fair Play for Game Stalls: Games should be clear, doable, and fun. Rules must be displayed openly and no rigged mechanics or impossible-to-win setups.",
            "Pricing Guidelines: Pricing to be submitted for approval on 15 April 2026 by 7 PM. Unfair or over-inflated pricing will be rejected.",
            "Token System Only: UPI/Cash transactions allowed to buy Tokens; only O-Week Tokens can be used to buy items/games.",
            "Stall Clean-Up is Mandatory: You trash it, you clean it. No mess left behind.",
            "Music Coordination: Get your own speaker/laptop if you plan to create a vibe around the stall.",
            "Safety Clause: Anything hazardous, offensive, or culturally insensitive = immediate stall shutdown.",
            "Time Discipline: All stalls must be ready by 5:00 PM and operate till 8:30 PM. No early wrapping.",
          ],
        },
      ],
    },
    {
      id: "sc-dramance",
      title: "Dramance (Drama + Dance) Wars",
      content: [
        { type: "heading", text: "1. Team Composition & Eligibility" },
        {
          type: "list",
          items: [
            "Gender Diversity: Every team must include both boys and girls. If there is less participation of any gender then there will be negative points for the same.",
            "Max Participation: Large-scale participation is encouraged. While there is no hard cap, points are awarded for involving the maximum number of eligible members in the activity.",
          ],
        },
        { type: "heading", text: "2. Performance Guidelines" },
        {
          type: "list",
          items: [
            "Time Limit: Performances must be between 6 and 8 minutes.",
            "The 30-70 Rule: Teams must have 30% of the time for dance and 70% for the skit.",
            "There may also be an opportunity for the best dancers in your class to earn you extra points!",
          ],
        },
        {
          type: "callout",
          text: "Penalty: A 5-point deduction will be applied for time overrun. If the team runs over 9 mins then they will be immediately disqualified.",
          variant: "warning",
        },
        { type: "heading", text: "3. Code of Conduct" },
        {
          type: "paragraph",
          text: "All participants are expected to maintain sportsmanship. Sabotage, inappropriate gestures will result in immediate disqualification.",
        },
      ],
    },
    {
      id: "sc-photography",
      title: "Photography — Shutter Island",
      content: [
        {
          type: "paragraph",
          text: "This is not a conventional photography contest. The focus is on storytelling through participation — sections are encouraged to use human formations, costumes, props, and campus backdrops to creatively interpret themes (e.g., Independence Day, Bollywood Sequence, Ambition, Why I'm Here).",
        },
        {
          type: "paragraph",
          text: "Each section receives a surprise theme every morning for five days. Within a stipulated time window, sections collaborate to conceptualize and submit one photograph interpreting the theme. Each submission must include a one-line caption. Points accumulate daily to determine the Section Champion.",
        },
        { type: "heading", text: "Format" },
        {
          type: "list",
          items: [
            "5 Days | Daily surprise theme",
            "Fixed submission window",
            "One entry per section per day",
            "Photograph + one-line caption",
            "Cumulative scoring",
          ],
        },
        { type: "heading", text: "Evaluation Criteria" },
        {
          type: "table",
          headers: ["Criteria", "Description", "Weightage"],
          rows: [
            ["Creativity", "Originality of concept, storytelling, and innovative interpretation of the theme", "25%"],
            ["Participation", "Involvement of section members, use of human formations, coordination", "25%"],
            ["Theme Adherence", "How clearly and effectively the photograph reflects the given theme", "25%"],
            ["Use of Campus", "Creative use of campus spaces, architecture, and surroundings as backdrop", "25%"],
          ],
        },
        { type: "heading", text: "Themes (Tentative — may change)" },
        {
          type: "table",
          headers: ["Day", "Theme", "Brief Interpretation"],
          rows: [
            ["Day 1", "High School Musical", "Group performance, dance freeze, or \"We're All in This Together\" style formation"],
            ["Day 2", "Avengers", "Superhero team lineup, action poses, or \"assemble\" moment"],
            ["Day 3", "The Office", "Workplace chaos, awkward meeting, or mock corporate scene"],
            ["Day 4", "Zombie Apocalypse", "Survival group, chase scene, or human vs zombie formation"],
            ["Day 5", "The Devil Wears Prada", "Fashion runway, boss-entry scene, or dramatic workplace moment"],
          ],
        },
      ],
    },
    {
      id: "sc-meme-wars",
      title: "Meme Wars",
      content: [
        {
          type: "paragraph",
          text: "Meme Wars is the ultimate battle of wit and creativity during O-Week! Sections compete to craft the funniest, most viral memes centered around ISB, O-Week moments, and pop culture. Unleash your section's meme-making mastery, rack up Instagram engagement, and crown yourselves the meme lords of Co'28.",
        },
        { type: "heading", text: "Categories" },
        {
          type: "table",
          headers: ["Category", "Format & What's Evaluated", "Submission"],
          rows: [
            ["Template-Based Meme", "Must use the organizer-released daily template. Judged on how creatively and humorously the section works within the given format.", "1 official entry per section per day, submitted to SPOC"],
            ["YSB Campus Meme", "Original meme built around a photo taken on the ISB campus. Judged on originality, campus relevance, and how well the photo ties into the meme.", "1 official entry per section per day, submitted to SPOC"],
            ["Open Category Meme", "Completely free format — template, campus photo, or anything else. Judged purely on creativity, humor, and relatability with no format restrictions.", "1 official entry per section per day, submitted to SPOC"],
            ["Instagram Engagement", "Unlimited memes posted on the section's <section>_co28 page with #ysbmemes. Score is based on cumulative likes, comments, and shares — essentially a crowd vote.", "No separate submission; accumulates automatically throughout the event"],
          ],
        },
        { type: "heading", text: "Key Details" },
        {
          type: "table",
          headers: ["Detail", "Info"],
          rows: [
            ["Duration", "Monday 13th April — Friday 18th April 2026 (5 days)"],
            ["Instagram Page", "Each section creates a page: <SectionName>_co28 (e.g., sectiona_co28)"],
            ["Required Hashtag", "#ysbmemes (posts without it won't count)"],
            ["What to Do", "Unlimited posts on Instagram and 3 official submissions per day to SPOC"],
          ],
        },
        { type: "heading", text: "Guidelines & Rules" },
        {
          type: "list",
          items: [
            "Use the term 'YSB' (not 'ISB') at all times.",
            "Every Instagram post must include #ysbmemes or it won't count.",
            "All memes must be approved by the SPOC before posting.",
            "Unapproved memes that are posted will result in immediate disqualification.",
            "Any guideline-violating meme that has been approved must be deleted immediately upon discovery.",
            "Absolutely no memes targeting CASHD and HCC, or other sensitive violations.",
            "Memes must be sensitive and respectful — no content that demeans individuals or groups.",
            "Follow all ISB marketing and branding policies.",
          ],
        },
        { type: "heading", text: "Judging Criteria" },
        {
          type: "table",
          headers: ["Judging Dimension", "What We Look For"],
          rows: [
            ["Creativity & Originality", "Fresh ideas, clever formats, unexpected twists"],
            ["Humor", "Actually funny — makes people laugh out loud"],
            ["Relevance", "Ties into O-Week, YSB life, or pop culture"],
            ["YSB Relatability", "Hits different for the Co'28 cohort"],
            ["Instagram Engagement", "Likes, comments & shares on your section page"],
          ],
        },
      ],
    },
    {
      id: "sc-quiz",
      title: "Quiz — Rapid Fire",
      content: [
        {
          type: "paragraph",
          text: "Rapid Fire Quiz is a fast-paced, individual knowledge battle powered by a live quiz platform (think Kahoot!). With 400 participants going head-to-head on questions spanning ISB, pop culture, business, science, arts, and more — speed and accuracy are everything. Scores roll up to your section, so every point you bag counts toward your cohort's glory.",
        },
        { type: "heading", text: "General Details" },
        {
          type: "table",
          headers: ["Detail", "Info"],
          rows: [
            ["Participants", "All all PGP YL Co'28 students"],
            ["Format", "Individual quiz via live platform (e.g. Kahoot)"],
            ["When", "Integrated into Khemka sessions — no separate time slot"],
            ["Scoring", "Based on accuracy + speed; section scores aggregate individual results"],
            ["Leaderboard", "Live leaderboard displayed throughout the quiz"],
          ],
        },
        { type: "heading", text: "How It Works" },
        {
          type: "list",
          items: [
            "The quiz runs during Khemka sessions — stay sharp, it can happen anytime.",
            "Join via your device using the session code shared by the organizers.",
            "Questions appear on screen; answer on your phone as fast as you can.",
            "Each correct answer earns points — the faster you answer, the more you score.",
            "A live leaderboard updates after each question so you always know where you stand.",
            "Your individual score is automatically added to your section's cumulative tally.",
            "There is one round only — no second chances, no elimination brackets.",
          ],
        },
        { type: "heading", text: "Question Categories" },
        {
          type: "paragraph",
          text: "Questions are designed to be inclusive and accessible for broad participation, with a mix of harder differentiating questions for top performers. Expect a spread across:",
        },
        {
          type: "list",
          items: [
            "YSB & Campus Life",
            "Pop Culture",
            "Business & Finance",
            "Science & Technology",
            "Arts & Culture",
            "Current Affairs",
          ],
        },
      ],
    },
  ],
};

// ─── Section 4: Strategy & Social Games ───

const STRATEGY_GAMES: RulebookSection = {
  id: "strategy-games",
  title: "Strategy Games",
  icon: "Swords",
  color: "text-red-600",
  emoji: "🎯",
  subsections: [
    {
      id: "sg-bbs",
      title: "Beg, Borrow, Steal",
      content: [
        {
          type: "table",
          headers: ["Detail", "Info"],
          rows: [
            ["Event Type", "Section Wars — Social Interaction Game"],
            ["SPOC", "Vasu Verma"],
            ["Start", "Sunday, 10:00 AM"],
            ["End", "Wednesday, 12:00 PM (Noon)"],
            ["Volunteers", "Orientation Week volunteers (assigned as coupon holders)"],
            ["Coupon Submission Deadline", "Wednesday, 12:00 PM sharp — to SPOC or Section SPOCs"],
          ],
        },
        { type: "heading", text: "Objective" },
        {
          type: "paragraph",
          text: "Break the ice, build your section, and out-collect everyone else. Beg, Borrow, Steal is a high-energy social game where students earn coupons from Orientation Week volunteers through genuine, memorable interaction. Every coupon carries hidden points. Every conversation counts. The section that banks the most points wins Section Wars points.",
        },
        { type: "heading", text: "How the Game Works" },
        {
          type: "list",
          items: [
            "Each Orientation Week volunteer carries a set of personalized coupons — their name, photo, or identifier printed on them.",
            "Coupon supply per volunteer is effectively unlimited. No participant should be turned away due to supply.",
            "Each volunteer's coupon carries a hidden point value (e.g., 2, 3, or 4 points). These values are NOT disclosed to participants.",
          ],
        },
        { type: "heading", text: "How to Earn a Coupon" },
        {
          type: "paragraph",
          text: "To earn a coupon from a volunteer, you must approach them and engage meaningfully. The volunteer awards coupons entirely at their own discretion. Simply showing up and asking is not enough.",
        },
        {
          type: "list",
          items: [
            "Introducing yourself in a creative or memorable way",
            "Completing a fun, spontaneous task set by the volunteer",
            "Having a genuine, interesting conversation that the volunteer finds noteworthy",
            "Demonstrating real curiosity about the volunteer's background or experience",
          ],
        },
        {
          type: "callout",
          text: "The Golden Rule: The volunteer decides. There are no appeals. If you didn't get a coupon, try harder — or come back with a better story.",
          variant: "warning",
        },
        { type: "heading", text: "Collection Limits" },
        {
          type: "list",
          items: [
            "A student may collect a maximum of 2 coupons from any single volunteer.",
            "There is no cap on total coupons collected across all volunteers.",
            "Collecting from more volunteers is always better — you don't know who has the highest point value.",
          ],
        },
        { type: "heading", text: "Coupon Custody" },
        {
          type: "list",
          items: [
            "Once you receive a coupon, you are fully responsible for its safekeeping.",
            "Lost, damaged, or destroyed coupons will not be replaced or compensated under any circumstances.",
            "Keep your coupons secure at all times. A lost coupon is a lost point.",
          ],
        },
        { type: "heading", text: "Submission" },
        {
          type: "list",
          items: [
            "All coupons must be submitted to Event SPOC or Section SPOCs by Wednesday, 12:00 PM.",
            "Daily EOD drop: Submit your day's collection to SPOCs at the end of each event day.",
            "Single final submission: Hold all coupons and submit everything together before the Wednesday 12:00 PM deadline.",
            "Late submissions will not be accepted. No exceptions.",
            "Coupons submitted after the deadline will receive zero points, regardless of value.",
          ],
        },
        { type: "heading", text: "Fair Play" },
        {
          type: "list",
          items: [
            "Duplicate, forged, or tampered coupons will result in disqualification of the student's entire submission.",
          ],
        },
        {
          type: "callout",
          text: "Volunteers are not required to be 'on duty' 24/7. They carry their coupons during normal Orientation Week activities — sessions, social hours, meals, and events. Use your windows wisely.",
          variant: "info",
        },
        { type: "heading", text: "Scoring & Section Wars" },
        {
          type: "list",
          items: [
            "Each coupon carries a hidden point value assigned to that volunteer.",
            "Your personal score = sum of all point values across all coupons you submit.",
            "Your section's score = sum of personal scores of all students in your section.",
            "The top 3 sections with the highest section scores win Section Wars points for this event.",
            "Individual scores are not ranked or announced. Only the section winner is declared.",
          ],
        },
        {
          type: "callout",
          text: "Why talk to everyone? Because you cannot know which volunteer carries higher-value coupons. Two students who collect the same number of coupons may score very differently based on whose coupons they collected.",
          variant: "tip",
        },
        { type: "heading", text: "Quick Reference" },
        {
          type: "table",
          headers: ["Rule", "Detail"],
          rows: [
            ["Game Window", "Sunday 10:00 AM — Wednesday 12:00 PM"],
            ["Earning Coupons", "Approach volunteers and engage meaningfully"],
            ["Coupon Limit per Volunteer", "Maximum 2 per student"],
            ["Points per Coupon", "Hidden — varies by volunteer"],
            ["Submission", "To SPOCs — daily EOD or all at once"],
            ["Submission Deadline", "Wednesday 12:00 PM — no late entries"],
            ["Transfers/Trades", "Strictly prohibited"],
          ],
        },
      ],
    },
    {
      id: "sg-mafia",
      title: "Mafia — Section Wars",
      content: [
        {
          type: "paragraph",
          text: "Mafia: Section Wars is a 6-section competitive social deduction game, with strategy, deceit, and coordination at its core. Players use BeReal to submit actions across six game sessions. Each section must outwit others, eliminate threats, and maximize their points.",
        },
        { type: "heading", text: "Game Structure" },
        {
          type: "table",
          headers: ["Detail", "Info"],
          rows: [
            ["Players per Section", "20"],
            ["Total Players", "120"],
            ["Game Days", "Wednesday 2nd half to Saturday 1st half"],
            ["Sessions", "Wed: Session B | Thu: Sessions A & B | Fri: Sessions A & B | Sat: Session A"],
            ["Total Sessions", "6"],
            ["Session A", "11:00 AM – 3:00 PM"],
            ["Session B", "6:00 PM – 10:00 PM"],
          ],
        },
        { type: "heading", text: "Role Distribution (Per Section)" },
        {
          type: "paragraph",
          text: "Roles are randomly assigned within each section and known only to that section.",
        },
        {
          type: "table",
          headers: ["Role", "Names", "Count", "Description"],
          rows: [
            ["Godfather", "RDX", "1", "Strategic leader of the mafia; enables kills; if dead the section cannot kill"],
            ["Henchmen", "Udai Bhai and Majnu Bhai", "2", "Operational mafia; each henchman can perform 1 kill per session"],
            ["Doctors", "Munna Bhai and Circuit", "2", "Can prevent one player from dying per session"],
            ["Detectives", "Raj Baadshah and ACP Pradyumn", "2", "Can attempt to uncover mafia identities, 1 combined per session"],
            ["Judge", "Admiral General/PM Aladeen", "1", "May choose to execute one person per session"],
            ["Reviver", "Mother India", "1", "Can revive one teammate if they die"],
            ["Suicide Bomber", "—", "1", "Kills their killer if killed by mafia; kills the judge + two others when executed by judge"],
            ["John Wick", "John Wick", "1", "Invincible except against the Judge's executions"],
            ["Villagers", "Villagers", "9", "Vote out; essential decoys and participants"],
          ],
        },
        { type: "heading", text: "Action Submission Protocol — BeReal" },
        {
          type: "list",
          items: [
            "The BeReal must clearly show the action-doer's face along with the person being killed (in case of mafia) or the name of the person being acted upon (judge, doctor, detective).",
            "Only moderators are to be added as BeReal friends.",
            "Please remove all friends from your BeReal during the game (else your identity might get revealed).",
            "Photos must be posted within the session window for the action to count.",
            "BeReal's real-time capture and timestamp validation serve as the audit mechanism.",
          ],
        },
        { type: "heading", text: "Allowed Actions Per Role Per Session" },
        {
          type: "table",
          headers: ["Role", "Actions"],
          rows: [
            ["Mafia team (Godfather/Henchmen)", "Max 2 kill submissions per session"],
            ["Detectives", "1 suspicion submission per session"],
            ["Doctor", "1 save submission per doctor"],
            ["Judge", "1 execution submission"],
            ["Suicide Bomber", "Passive (triggers only when killed)"],
            ["Reviver", "Passive (chooses after their death)"],
            ["John Wick", "Passive (only affected by the judge)"],
            ["Villager", "No action"],
          ],
        },
        {
          type: "callout",
          text: "Submissions made outside session window or with incorrect location are invalid.",
          variant: "warning",
        },
        { type: "heading", text: "Mafia (Godfather + Henchmen)" },
        {
          type: "list",
          items: [
            "Each Henchman must submit a BeReal photo of the target for a kill. The photo must clearly show the face of the target.",
            "BeReal only allows 3 posts per day, so please do not post random photos.",
            "If two mafia teams submit for the same target, the earliest timestamp wins.",
            "If the Godfather dies, the section's henchmen can no longer submit kills, even if Henchmen are alive.",
            "The Godfather can kill people only if both the Henchmen are eliminated.",
            "Mafia cannot kill players from their own section.",
            "A maximum of 9 mafia kills per session is allowed. 1 kill per Section + 3 additional kills (first 3 sections to send 2 kills will only get this added benefit).",
          ],
        },
        {
          type: "callout",
          text: "If 4 or more people from a section are killed by mafia in one session, that section will be allowed 1 extra kill and 1 extra save in the next round.",
          variant: "info",
        },
        { type: "heading", text: "Detectives" },
        {
          type: "list",
          items: [
            "Must take a BeReal in Goel's.",
            "The photo must include themselves and must include a visible or stated name of the person suspected (e.g., a chit with the full name and section).",
            "Only one suspicion submission per team per session.",
            "At the end of the session, the Detective is informed whether their suspicion was correct.",
            "Incorrect guesses carry no penalty.",
          ],
        },
        { type: "heading", text: "Doctors" },
        {
          type: "list",
          items: [
            "Must take a BeReal in the atrium.",
            "The photo must include themselves and must include a visible or stated name of the person being saved.",
            "One save per doctor per session.",
            "The save is valid only if the saved person was actually targeted in that session.",
            "Doctors are not informed whether their save was successful.",
            "Incorrect saves have no penalty.",
            "Can save any player from any section, including themselves.",
            "The doctor can only save people killed by the mafia. Any execution via judge or death by suicide bomber will not be a successful save.",
          ],
        },
        { type: "heading", text: "Judge" },
        {
          type: "list",
          items: [
            "Submit a BeReal in Goel's.",
            "The photo must include themselves and must include a visible or stated name of the person being targeted.",
            "If the executed player is a Godfather or Henchman, section earns points.",
            "If the executed player is any other role, section incurs a penalty of -50 points.",
            "If the Judge dies, the section can no longer execute suspected mafias.",
            "Special Rule: The judge is the only one who can execute John Wick.",
          ],
        },
        { type: "heading", text: "Suicide Bomber" },
        {
          type: "list",
          items: [
            "If killed by Mafia, they instantly kill their killer.",
            "If executed by judge, they instantly kill their judge and choose 2 additional players (from any section) to die with them.",
            "These 2 will be confirmed by the moderator after the session ends, no photos needed.",
            "Suicide Bomber does not activate if they are saved by a Doctor.",
            "If a suicide bomber chooses the suicide bomber of another section, it will trigger a chain reaction!",
          ],
        },
        { type: "heading", text: "Reviver" },
        {
          type: "list",
          items: [
            "If the Reviver dies, they must choose one dead player from their section to revive.",
            "This decision will be confirmed by the moderators after the session ends but before the session result is announced, no photos needed.",
            "They cannot revive themselves.",
            "The revived player returns with their original role and abilities.",
          ],
        },
        { type: "heading", text: "John Wick" },
        {
          type: "list",
          items: [
            "Cannot be killed by Mafia or suicide bomber.",
            "Can only be killed if executed by a Judge or voted out by villagers.",
          ],
        },
        { type: "heading", text: "Villagers" },
        {
          type: "list",
          items: [
            "Each round, a survey will be sent out for the villagers on Microsoft Forms. If 20% of the surviving villagers vote for a single person, that person will be eliminated from the game without triggering any of their powers. They cannot be revived and cannot detonate the suicide bomber and neither can they revive anyone.",
          ],
        },
        {
          type: "paragraph",
          text: "No section gets points for voting out, but:",
        },
        {
          type: "list",
          items: [
            "If a villager/doctor/detective/judge/reviver of a section is voted out, that section gets 150 points.",
            "If a godfather/henchman is voted out, then 50 points are deducted from that section.",
            "No deduction or addition if the suicide bomber/John Wick is voted out.",
          ],
        },
        { type: "heading", text: "Scoring Table" },
        {
          type: "table",
          headers: ["Action", "By Godfather/Henchman", "By Suicide Bomber", "By Judge", "By Doctor", "By Detective"],
          rows: [
            ["Kill/Execute Godfather", "80", "80", "120", "—", "—"],
            ["Kill/Execute Henchman", "50", "50", "70", "—", "—"],
            ["Kill/Execute Doctor", "30", "25", "-50", "—", "—"],
            ["Kill/Execute Judge", "40", "25", "-50", "—", "—"],
            ["Kill/Execute Detective", "60", "25", "-50", "—", "—"],
            ["Kill/Execute Suicide Bomber", "20", "25", "—", "—", "—"],
            ["Kill/Execute Reviver", "70", "25", "-50", "—", "—"],
            ["Kill/Execute Villager", "10", "25", "-50", "—", "—"],
            ["Kill/Execute John Wick", "—", "—", "90", "—", "—"],
            ["Successfully Save Godfather", "—", "—", "—", "10", "—"],
            ["Successfully Save Henchman", "—", "—", "—", "20", "—"],
            ["Successfully Save Doctor/Judge/Detective", "—", "—", "—", "40", "—"],
            ["Successfully Save Reviver/Suicide Bomber", "—", "—", "—", "30", "—"],
            ["Successfully Save Villager", "—", "—", "—", "50", "—"],
            ["Successful Suspicion (Detective)", "—", "—", "—", "—", "50"],
            ["Failed Suspicion", "—", "—", "—", "—", "—"],
          ],
        },
        {
          type: "paragraph",
          text: "Scores are credited to the section of the acting role.",
        },
        { type: "heading", text: "Session Result Metrics" },
        {
          type: "list",
          items: [
            "Results from Session N will be announced 1 hour before Session N+1 begins.",
            "Results include: Names of people who died in that session; All roles at time of death (no specific roles of individual people).",
            "Never revealed: Who attacked, saved, or executed whom; Whether someone was saved; Who used a power.",
          ],
        },
        { type: "heading", text: "Section Collusion" },
        {
          type: "list",
          items: [
            "Collusion is allowed between sections.",
            "No official support or penalty from moderators.",
            "Any benefits, deals, or betrayals are enforced only by the players themselves.",
          ],
        },
        { type: "heading", text: "Violation & Disputes" },
        {
          type: "list",
          items: [
            "All disputes are resolved by the moderator panel.",
            "Invalid submissions (e.g., wrong location or late BeReals) are automatically disqualified.",
            "If multiple actions target the same player, only the first to act will be considered.",
            "If a mafia A targets a mafia B who targets a different role, Mafia B's kill will be considered, if the timestamp of that kill is before mafia A's kill.",
          ],
        },
        { type: "heading", text: "Winning" },
        {
          type: "list",
          items: [
            "The section with the highest cumulative score after all 6 sessions wins.",
            "Tiebreaker (if needed): Number of surviving players → Number of successful kills → Coin toss.",
          ],
        },
        {
          type: "callout",
          text: "In case of any doubts, please reach out to the Event SPOCs or your section SPOCs at the earliest. Preferably before the game begins on Wednesday.",
          variant: "info",
        },
      ],
    },
    {
      id: "sg-wheres-waldo",
      title: "Where's Waldo",
      content: [
        {
          type: "paragraph",
          text: "There is a person in your section. This person has an allotted quad, even an allotted roll number. And that person has even performed on stage in Khemka. But doesn't belong in your cohort and is an alum.",
        },
        {
          type: "paragraph",
          text: "Your task, should you choose to accept it (and there are a lot of points for it!), is to find that person and report it to us. The report format should be a video recording of that person being \"sus\" or/and you explaining their sus behavior.",
        },
        {
          type: "callout",
          text: "This has individual submissions and they have to be sent to the email: mannat_mangal_PGP2026@isb.edu",
          variant: "info",
        },
        {
          type: "paragraph",
          text: "The section which rightly identifies their decoy person gets 110 section points.",
        },
      ],
    },
  ],
};

// ─── Export ───

export const RULEBOOK_SECTIONS: RulebookSection[] = [
  PROFESSIONAL_EVENTS,
  SPORTS_EVENTS,
  SOCIAL_CULTURAL,
  STRATEGY_GAMES,
];

// ─── Search Index ───

export function buildRulebookSearchIndex(): {
  subsectionId: string;
  sectionId: string;
  sectionTitle: string;
  sectionEmoji: string;
  subsectionTitle: string;
  text: string;
}[] {
  const index: {
    subsectionId: string;
    sectionId: string;
    sectionTitle: string;
    sectionEmoji: string;
    subsectionTitle: string;
    text: string;
  }[] = [];

  for (const section of RULEBOOK_SECTIONS) {
    for (const sub of section.subsections) {
      const parts: string[] = [sub.title.toLowerCase()];
      for (const block of sub.content) {
        switch (block.type) {
          case "paragraph":
          case "heading":
          case "callout":
            parts.push(block.text.toLowerCase());
            break;
          case "list":
            parts.push(...block.items.map((i) => i.toLowerCase()));
            break;
          case "table":
            parts.push(...block.headers.map((h) => h.toLowerCase()));
            for (const row of block.rows) {
              parts.push(...row.map((c) => c.toLowerCase()));
            }
            break;
          case "contact":
            parts.push(block.label.toLowerCase(), block.value.toLowerCase());
            break;
        }
      }

      index.push({
        subsectionId: sub.id,
        sectionId: section.id,
        sectionTitle: section.title,
        sectionEmoji: section.emoji,
        subsectionTitle: sub.title,
        text: parts.join(" "),
      });
    }
  }

  return index;
}
