-- ============================================================================
-- PGP YL O-Week — QR token 6-digit fallback code + 60s rotation
-- ============================================================================
-- Adds a short numeric code that is displayed alongside the QR code so a
-- student whose camera won't cooperate can type it in manually. The code is
-- generated by the rotate-qr-token edge function on every rotation.
-- Also shortens the token validity window to 60 seconds (1-minute rotation).
-- ============================================================================

alter table public.qr_tokens
  add column if not exists code text;

-- 60-second validity window (rotation cadence is also 1 minute via pg_cron)
alter table public.qr_tokens
  alter column valid_until set default (now() + interval '60 seconds');

-- Fast lookup when a student enters the 6-digit code manually.
-- Partial index keeps it lean (only rows that have a code).
create index if not exists qr_tokens_code_idx
  on public.qr_tokens (code)
  where code is not null;
